---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{.PSCMS_UI_NAME}}
  labels:
    cert-manager.io/solver: http01
  annotations:
    cert-manager.io/enabled: "true"
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-send-timeout: "3600"
    ingress.kubernetes.io/proxy-read-timeout: "3600"
    ingress.kubernetes.io/proxy-body-size: "50m"
    ingress.kubernetes.io/whitelist-source-range: {{.INGRESS_WHITELISTED_IPS}}
spec:
  rules:
  - host: {{.PSCMS_UI_URL}}
    http:
      paths:
      - backend:
          serviceName: {{.PSCMS_UI_NAME}}
          servicePort: 8443
        path: /
  tls:
  - hosts:
    - {{.PSCMS_UI_URL}}
    secretName: {{.PSCMS_UI_URL}}-cmio
