---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{.PSCMS_UI_NAME}}
spec:
  egress:
  - {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-internal
    ports:
      - port: 8443
        protocol: TCP
  podSelector:
    matchLabels:
      name: {{.PSCMS_UI_NAME}}
  policyTypes:
    - Ingress
    - Egress
