---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.PSCMS_UI_NAME}}
  name: {{.PSCMS_UI_NAME}}
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    name: {{.PSCMS_UI_NAME}}
