export const testData = {
  formData: {
    id: 'id',
    title: 'formTitle',
    name: 'formName',
    formKey: 'formKey',
    type: 'form',
    versionId: 'version',
    components: [
      {
        id: 'eoduazt',
        key: 'textField1',
        case: '',
        mask: false,
        tags: '',
        type: 'textfield',
        input: true,
        label: 'Text Field',
        logic: [],
        hidden: false,
        prefix: '',
        suffix: '',
        unique: false,
        validate: {
          json: '',
          custom: '',
          unique: false,
          pattern: '',
          multiple: false,
          required: true,
          maxLength: '',
          minLength: '',
          customMessage: '',
          customPrivate: false,
          strictDateValidation: false,
        },
        widget: {
          type: 'input',
        },
      },
      {
        id: 'eoduazg',
        key: 'textField2',
        case: '',
        mask: false,
        tags: '',
        type: 'textfield',
        input: true,
        label: 'Text Field',
        logic: [],
        hidden: false,
        prefix: '',
        suffix: '',
        unique: false,
        validate: {
          json: '',
          custom: '',
          unique: false,
          pattern: '',
          multiple: false,
          required: true,
          maxLength: '',
          minLength: '',
          customMessage: '',
          customPrivate: false,
          strictDateValidation: false,
        },
        widget: {
          type: 'input',
        },
      },
      {
        id: 'e23op57',
        key: 'submit',
        size: 'md',
        type: 'button',
        block: false,
        input: true,
        label: 'Submit',
        theme: 'primary',
        action: 'submit',
        hidden: false,
        prefix: '',
        suffix: '',
        unique: false,
        widget: {
          type: 'input',
        },
      },
    ],
  },
  formErrors: [
    {
      component: {
        id: 'eoduazt',
        key: 'textField1',
      },
      message: 'Textfield is required',
    },
    {
      component: {
        id: 'eoduazg',
        key: 'textField2',
      },
      message: 'Textfield is required',
    },
  ],
};
