name: Publish Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: 'pscms-ui'
      REPO: 'ukhomeofficedigital/pscms-ui'
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        working-directory: ./client
        run: npm install
      - name: Run tests with coverage
        working-directory: ./client
        run: npm run test-coverage
        env:
          CI: true
      - uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
          architecture: 'x64'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run build
        run: ./gradlew clean assemble
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE }}:latest
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ env.REPO}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: quay.io
          cache: true
          snapshot: true
          tags: "${{ github.sha }}"
      - uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Github # default: 8398a7@action-slack
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
